
# path for .env/.env.local is read relative to docker-compose
services:
  frontend:
    build: 
    # fonlder we're building the image from
      context: ../front-end
    # the Dockerfile to run for the build | not needed unless using a custom Dockerfile
      dockerfile: Dockerfile.dev 
    ports:
      - "3002:3000"
      #  will change for prod
    env_file:
      - .env
    environment:
    # this is needed since we're using CRA
      HOST: 0.0.0.0
      # if unspecified will be pushed out by the .env.local
      PORT: 3000
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_CLERK_PUBLISHABLE_KEY: ${REACT_APP_CLERK_PUBLISHABLE_KEY}
    volumes:
      - ../front-end:/app
      - /app/node_modules
    depends_on:
      - backend
      #NEW: to make sure we don't run tests before frontend is up
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile.dev
    ports: 
      - "5002:5001"
    env_file:
    #  will change for prod
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      # prob change later? check .env.local
      VARIATION_EMAIL: ${VARIATION_EMAIL}
      VARIATION_PASSWORD: ${VARIATION_PASSWORD}
      #
    volumes:
      - ../back-end:/app
      - /app/node_modules
    # depends_on:
    #   - prob MongoDB
    #NEW: to make sure we don't run tests before backen is up
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  cypress: 
    image: cypress/included:latest
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      # persists dependencies for frontend and backend
      - /app/front-end/node_modules
      - /app/back-end/node_modules
      # persist Cypress outputs outside the container for debugging
      - ./cypress-results:/app/cypress/results
      - ./cypress-screenshots:/app/cypress/screenshots
      - ./cypress-videos:/app/cypress/videos
    environment:
      CYPRESS_baseUrl: http://frontend:3000
      CYPRESS_API_BASE_URL: http://backend:5001
      REACT_APP_CLERK_PUBLISHABLE_KEY: ${REACT_APP_CLERK_PUBLISHABLE_KEY}
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    command: npx cypress run
