# path for .env/.env.local is read relative to docker-compose
services:
  frontend:
    build:
      # fonlder we're building the image from
      context: ../front-end
      # the Dockerfile to run for the build | not needed unless using a custom Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002" #  will change for prod
    env_file:
      # makes sure we load all the necessary vars int othe container
      - .env
    environment:
      # this is needed since we're using CRA
      HOST: 0.0.0.0
      # if unspecified will be pushed out by the .env.local
      PORT: 3002
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_CLERK_PUBLISHABLE_KEY: ${REACT_APP_CLERK_PUBLISHABLE_KEY}
    volumes:
      - ../front-end:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile.dev
    ports:
      - "5002:5002"
    env_file:
      #  will change for prod
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      # prob change later? check .env.local
      VARIATION_EMAIL: ${VARIATION_EMAIL}
      VARIATION_PASSWORD: ${VARIATION_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
      # reads mail identity
      NOREPLY_APP_PASSWORD: ${NOREPLY_APP_PASSWORD}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_FROM_ADDR: ${MAIL_FROM_ADDR}
      MAIL_AUTH_USER: ${MAIL_AUTH_USER}
    volumes:
      - ../back-end:/app
      - /app/node_modules
    # depends_on:
    #   - prob MongoDB
