
# to build use: 
# docker-compose -p variation up --build

services:
  frontend:
    build: 
    # fonlder we're building the image from
      context: ../front-end
    # the Dockerfile to run for the build | not needed unless using a custom Dockerfile
      dockerfile: Dockerfile.dev 
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
    # this is needed since we're using CRA
      - HOST=0.0.0.0
      # if unspecified will be pushed out by the .env.local
      - PORT=3000
      - REACT_APP_API_URL
      - REACT_APP_CLERK_PUBLISHABLE_KEY
    volumes:
      - ../front-end:/app
      - /app/node_modules
    # depends_on:
    #   - backend
  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile.dev
    ports: 
      - "5000:5000"
    env_file:
      - .env.local
    environment:
      - PORT: ${BACKEND_PORT}
      - MONGO_URI: ${MONGO_URI}
      - CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      # prob change later? check .env.local
      - VARIATION_EMAIL: ${VARIATION_EMAIL}
      - VARIATION_PASSWORD: ${VARIATION_PASSWORD}
      #
    volumes:
      - ../back-end:/app
      - /app/node_modules
    # depends_on:
    #   - prob MongoDB