
# path for .env/.env.local is read relative to docker-compose
services:
  frontend:
    build: 
    # fonlder we're building the image from
      context: ../front-end
    # the Dockerfile to run for the build | not needed unless using a custom Dockerfile
      dockerfile: Dockerfile.dev 
    ports:
      - "3002:3000"
      #  will change for prod
    env_file:
      - .env
    environment:
    # this is needed since we're using CRA
      HOST: 0.0.0.0
      # if unspecified will be pushed out by the .env.local
      PORT: 3000
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      REACT_APP_CLERK_PUBLISHABLE_KEY: ${REACT_APP_CLERK_PUBLISHABLE_KEY}
    volumes:
      - ../front-end:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile.dev
    ports: 
      - "5002:5001"
    env_file:
    #  will change for prod
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      CLERK_PUBLISHABLE_KEY: ${CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      # prob change later? check .env.local
      VARIATION_EMAIL: ${VARIATION_EMAIL}
      VARIATION_PASSWORD: ${VARIATION_PASSWORD}
      #
    volumes:
      - ../back-end:/app
      - /app/node_modules
    # depends_on:
    #   - prob MongoDB
  cypress: 
    image: cypress/included:latest
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      CYPRESS_baseUrl: http://frontend:3000
      CYPRESS_API_BASE_URL: http://backend:5001
    depends_on:
      - frontend
      - backend
    command: npx cypress run
